/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsoleIndexRouteImport } from './routes/_console/index'
import { Route as ConsoleAuditLogsIndexRouteImport } from './routes/_console/audit-logs/index'
import { Route as ConsoleBlogIndexRouteImport } from './routes/_console/blog/index'
import { Route as ConsoleBusinessesIndexRouteImport } from './routes/_console/businesses/index'
import { Route as ConsoleBusinessesIdRouteImport } from './routes/_console/businesses/$id'
import { Route as ConsoleCategoriesIndexRouteImport } from './routes/_console/categories/index'
import { Route as ConsoleCouponsIndexRouteImport } from './routes/_console/coupons/index'
import { Route as ConsoleCustomersIndexRouteImport } from './routes/_console/customers/index'
import { Route as ConsoleCustomersIdRouteImport } from './routes/_console/customers/$id'
import { Route as ConsoleInventoryIndexRouteImport } from './routes/_console/inventory/index'
import { Route as ConsoleOrdersIndexRouteImport } from './routes/_console/orders/index'
import { Route as ConsoleOrdersOrderNumberRouteImport } from './routes/_console/orders/$orderNumber'
import { Route as ConsolePricingIndexRouteImport } from './routes/_console/pricing/index'
import { Route as ConsoleProductsIndexRouteImport } from './routes/_console/products/index'
import { Route as ConsoleProductsIdRouteImport } from './routes/_console/products/$id'
import { Route as ConsoleProductsNewRouteImport } from './routes/_console/products/new'
import { Route as ConsoleReviewsIndexRouteImport } from './routes/_console/reviews/index'
import { Route as ConsoleRfqsIndexRouteImport } from './routes/_console/rfqs/index'
import { Route as ConsoleRfqsRfqNumberRouteImport } from './routes/_console/rfqs/$rfqNumber'
import { Route as ConsoleSettingsIndexRouteImport } from './routes/_console/settings/index'
import { Route as ConsoleSupportIndexRouteImport } from './routes/_console/support/index'
import { Route as ConsoleSupportTicketNumberRouteImport } from './routes/_console/support/$ticketNumber'

const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAuditLogsIndexRoute = ConsoleAuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleBlogIndexRoute = ConsoleBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleBusinessesIndexRoute = ConsoleBusinessesIndexRouteImport.update({
  id: '/businesses/',
  path: '/businesses/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleBusinessesIdRoute = ConsoleBusinessesIdRouteImport.update({
  id: '/businesses/$id',
  path: '/businesses/$id',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleCategoriesIndexRoute = ConsoleCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleCouponsIndexRoute = ConsoleCouponsIndexRouteImport.update({
  id: '/coupons/',
  path: '/coupons/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleCustomersIndexRoute = ConsoleCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleCustomersIdRoute = ConsoleCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleInventoryIndexRoute = ConsoleInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleOrdersIndexRoute = ConsoleOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleOrdersOrderNumberRoute =
  ConsoleOrdersOrderNumberRouteImport.update({
    id: '/orders/$orderNumber',
    path: '/orders/$orderNumber',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsolePricingIndexRoute = ConsolePricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleProductsIndexRoute = ConsoleProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleProductsIdRoute = ConsoleProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleProductsNewRoute = ConsoleProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleReviewsIndexRoute = ConsoleReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleRfqsIndexRoute = ConsoleRfqsIndexRouteImport.update({
  id: '/rfqs/',
  path: '/rfqs/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleRfqsRfqNumberRoute = ConsoleRfqsRfqNumberRouteImport.update({
  id: '/rfqs/$rfqNumber',
  path: '/rfqs/$rfqNumber',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsIndexRoute = ConsoleSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSupportIndexRoute = ConsoleSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSupportTicketNumberRoute =
  ConsoleSupportTicketNumberRouteImport.update({
    id: '/support/$ticketNumber',
    path: '/support/$ticketNumber',
    getParentRoute: () => ConsoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ConsoleIndexRoute
  '/login': typeof LoginRoute
  '/businesses/$id': typeof ConsoleBusinessesIdRoute
  '/customers/$id': typeof ConsoleCustomersIdRoute
  '/orders/$orderNumber': typeof ConsoleOrdersOrderNumberRoute
  '/products/$id': typeof ConsoleProductsIdRoute
  '/products/new': typeof ConsoleProductsNewRoute
  '/rfqs/$rfqNumber': typeof ConsoleRfqsRfqNumberRoute
  '/support/$ticketNumber': typeof ConsoleSupportTicketNumberRoute
  '/audit-logs/': typeof ConsoleAuditLogsIndexRoute
  '/blog/': typeof ConsoleBlogIndexRoute
  '/businesses/': typeof ConsoleBusinessesIndexRoute
  '/categories/': typeof ConsoleCategoriesIndexRoute
  '/coupons/': typeof ConsoleCouponsIndexRoute
  '/customers/': typeof ConsoleCustomersIndexRoute
  '/inventory/': typeof ConsoleInventoryIndexRoute
  '/orders/': typeof ConsoleOrdersIndexRoute
  '/pricing/': typeof ConsolePricingIndexRoute
  '/products/': typeof ConsoleProductsIndexRoute
  '/reviews/': typeof ConsoleReviewsIndexRoute
  '/rfqs/': typeof ConsoleRfqsIndexRoute
  '/settings/': typeof ConsoleSettingsIndexRoute
  '/support/': typeof ConsoleSupportIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof ConsoleIndexRoute
  '/businesses/$id': typeof ConsoleBusinessesIdRoute
  '/customers/$id': typeof ConsoleCustomersIdRoute
  '/orders/$orderNumber': typeof ConsoleOrdersOrderNumberRoute
  '/products/$id': typeof ConsoleProductsIdRoute
  '/products/new': typeof ConsoleProductsNewRoute
  '/rfqs/$rfqNumber': typeof ConsoleRfqsRfqNumberRoute
  '/support/$ticketNumber': typeof ConsoleSupportTicketNumberRoute
  '/audit-logs': typeof ConsoleAuditLogsIndexRoute
  '/blog': typeof ConsoleBlogIndexRoute
  '/businesses': typeof ConsoleBusinessesIndexRoute
  '/categories': typeof ConsoleCategoriesIndexRoute
  '/coupons': typeof ConsoleCouponsIndexRoute
  '/customers': typeof ConsoleCustomersIndexRoute
  '/inventory': typeof ConsoleInventoryIndexRoute
  '/orders': typeof ConsoleOrdersIndexRoute
  '/pricing': typeof ConsolePricingIndexRoute
  '/products': typeof ConsoleProductsIndexRoute
  '/reviews': typeof ConsoleReviewsIndexRoute
  '/rfqs': typeof ConsoleRfqsIndexRoute
  '/settings': typeof ConsoleSettingsIndexRoute
  '/support': typeof ConsoleSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_console': typeof ConsoleRouteWithChildren
  '/login': typeof LoginRoute
  '/_console/': typeof ConsoleIndexRoute
  '/_console/businesses/$id': typeof ConsoleBusinessesIdRoute
  '/_console/customers/$id': typeof ConsoleCustomersIdRoute
  '/_console/orders/$orderNumber': typeof ConsoleOrdersOrderNumberRoute
  '/_console/products/$id': typeof ConsoleProductsIdRoute
  '/_console/products/new': typeof ConsoleProductsNewRoute
  '/_console/rfqs/$rfqNumber': typeof ConsoleRfqsRfqNumberRoute
  '/_console/support/$ticketNumber': typeof ConsoleSupportTicketNumberRoute
  '/_console/audit-logs/': typeof ConsoleAuditLogsIndexRoute
  '/_console/blog/': typeof ConsoleBlogIndexRoute
  '/_console/businesses/': typeof ConsoleBusinessesIndexRoute
  '/_console/categories/': typeof ConsoleCategoriesIndexRoute
  '/_console/coupons/': typeof ConsoleCouponsIndexRoute
  '/_console/customers/': typeof ConsoleCustomersIndexRoute
  '/_console/inventory/': typeof ConsoleInventoryIndexRoute
  '/_console/orders/': typeof ConsoleOrdersIndexRoute
  '/_console/pricing/': typeof ConsolePricingIndexRoute
  '/_console/products/': typeof ConsoleProductsIndexRoute
  '/_console/reviews/': typeof ConsoleReviewsIndexRoute
  '/_console/rfqs/': typeof ConsoleRfqsIndexRoute
  '/_console/settings/': typeof ConsoleSettingsIndexRoute
  '/_console/support/': typeof ConsoleSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/businesses/$id'
    | '/customers/$id'
    | '/orders/$orderNumber'
    | '/products/$id'
    | '/products/new'
    | '/rfqs/$rfqNumber'
    | '/support/$ticketNumber'
    | '/audit-logs/'
    | '/blog/'
    | '/businesses/'
    | '/categories/'
    | '/coupons/'
    | '/customers/'
    | '/inventory/'
    | '/orders/'
    | '/pricing/'
    | '/products/'
    | '/reviews/'
    | '/rfqs/'
    | '/settings/'
    | '/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/businesses/$id'
    | '/customers/$id'
    | '/orders/$orderNumber'
    | '/products/$id'
    | '/products/new'
    | '/rfqs/$rfqNumber'
    | '/support/$ticketNumber'
    | '/audit-logs'
    | '/blog'
    | '/businesses'
    | '/categories'
    | '/coupons'
    | '/customers'
    | '/inventory'
    | '/orders'
    | '/pricing'
    | '/products'
    | '/reviews'
    | '/rfqs'
    | '/settings'
    | '/support'
  id:
    | '__root__'
    | '/_console'
    | '/login'
    | '/_console/'
    | '/_console/businesses/$id'
    | '/_console/customers/$id'
    | '/_console/orders/$orderNumber'
    | '/_console/products/$id'
    | '/_console/products/new'
    | '/_console/rfqs/$rfqNumber'
    | '/_console/support/$ticketNumber'
    | '/_console/audit-logs/'
    | '/_console/blog/'
    | '/_console/businesses/'
    | '/_console/categories/'
    | '/_console/coupons/'
    | '/_console/customers/'
    | '/_console/inventory/'
    | '/_console/orders/'
    | '/_console/pricing/'
    | '/_console/products/'
    | '/_console/reviews/'
    | '/_console/rfqs/'
    | '/_console/settings/'
    | '/_console/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsoleRoute: typeof ConsoleRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/': {
      id: '/_console/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/audit-logs/': {
      id: '/_console/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof ConsoleAuditLogsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/blog/': {
      id: '/_console/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof ConsoleBlogIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/businesses/': {
      id: '/_console/businesses/'
      path: '/businesses'
      fullPath: '/businesses/'
      preLoaderRoute: typeof ConsoleBusinessesIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/businesses/$id': {
      id: '/_console/businesses/$id'
      path: '/businesses/$id'
      fullPath: '/businesses/$id'
      preLoaderRoute: typeof ConsoleBusinessesIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/categories/': {
      id: '/_console/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof ConsoleCategoriesIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/coupons/': {
      id: '/_console/coupons/'
      path: '/coupons'
      fullPath: '/coupons/'
      preLoaderRoute: typeof ConsoleCouponsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/customers/': {
      id: '/_console/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof ConsoleCustomersIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/customers/$id': {
      id: '/_console/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof ConsoleCustomersIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/inventory/': {
      id: '/_console/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof ConsoleInventoryIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/orders/': {
      id: '/_console/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof ConsoleOrdersIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/orders/$orderNumber': {
      id: '/_console/orders/$orderNumber'
      path: '/orders/$orderNumber'
      fullPath: '/orders/$orderNumber'
      preLoaderRoute: typeof ConsoleOrdersOrderNumberRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/pricing/': {
      id: '/_console/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof ConsolePricingIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/products/': {
      id: '/_console/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ConsoleProductsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/products/$id': {
      id: '/_console/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ConsoleProductsIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/products/new': {
      id: '/_console/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ConsoleProductsNewRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/reviews/': {
      id: '/_console/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ConsoleReviewsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/rfqs/': {
      id: '/_console/rfqs/'
      path: '/rfqs'
      fullPath: '/rfqs/'
      preLoaderRoute: typeof ConsoleRfqsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/rfqs/$rfqNumber': {
      id: '/_console/rfqs/$rfqNumber'
      path: '/rfqs/$rfqNumber'
      fullPath: '/rfqs/$rfqNumber'
      preLoaderRoute: typeof ConsoleRfqsRfqNumberRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/settings/': {
      id: '/_console/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ConsoleSettingsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/support/': {
      id: '/_console/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof ConsoleSupportIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/support/$ticketNumber': {
      id: '/_console/support/$ticketNumber'
      path: '/support/$ticketNumber'
      fullPath: '/support/$ticketNumber'
      preLoaderRoute: typeof ConsoleSupportTicketNumberRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleBusinessesIdRoute: typeof ConsoleBusinessesIdRoute
  ConsoleCustomersIdRoute: typeof ConsoleCustomersIdRoute
  ConsoleOrdersOrderNumberRoute: typeof ConsoleOrdersOrderNumberRoute
  ConsoleProductsIdRoute: typeof ConsoleProductsIdRoute
  ConsoleProductsNewRoute: typeof ConsoleProductsNewRoute
  ConsoleRfqsRfqNumberRoute: typeof ConsoleRfqsRfqNumberRoute
  ConsoleSupportTicketNumberRoute: typeof ConsoleSupportTicketNumberRoute
  ConsoleAuditLogsIndexRoute: typeof ConsoleAuditLogsIndexRoute
  ConsoleBlogIndexRoute: typeof ConsoleBlogIndexRoute
  ConsoleBusinessesIndexRoute: typeof ConsoleBusinessesIndexRoute
  ConsoleCategoriesIndexRoute: typeof ConsoleCategoriesIndexRoute
  ConsoleCouponsIndexRoute: typeof ConsoleCouponsIndexRoute
  ConsoleCustomersIndexRoute: typeof ConsoleCustomersIndexRoute
  ConsoleInventoryIndexRoute: typeof ConsoleInventoryIndexRoute
  ConsoleOrdersIndexRoute: typeof ConsoleOrdersIndexRoute
  ConsolePricingIndexRoute: typeof ConsolePricingIndexRoute
  ConsoleProductsIndexRoute: typeof ConsoleProductsIndexRoute
  ConsoleReviewsIndexRoute: typeof ConsoleReviewsIndexRoute
  ConsoleRfqsIndexRoute: typeof ConsoleRfqsIndexRoute
  ConsoleSettingsIndexRoute: typeof ConsoleSettingsIndexRoute
  ConsoleSupportIndexRoute: typeof ConsoleSupportIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleBusinessesIdRoute: ConsoleBusinessesIdRoute,
  ConsoleCustomersIdRoute: ConsoleCustomersIdRoute,
  ConsoleOrdersOrderNumberRoute: ConsoleOrdersOrderNumberRoute,
  ConsoleProductsIdRoute: ConsoleProductsIdRoute,
  ConsoleProductsNewRoute: ConsoleProductsNewRoute,
  ConsoleRfqsRfqNumberRoute: ConsoleRfqsRfqNumberRoute,
  ConsoleSupportTicketNumberRoute: ConsoleSupportTicketNumberRoute,
  ConsoleAuditLogsIndexRoute: ConsoleAuditLogsIndexRoute,
  ConsoleBlogIndexRoute: ConsoleBlogIndexRoute,
  ConsoleBusinessesIndexRoute: ConsoleBusinessesIndexRoute,
  ConsoleCategoriesIndexRoute: ConsoleCategoriesIndexRoute,
  ConsoleCouponsIndexRoute: ConsoleCouponsIndexRoute,
  ConsoleCustomersIndexRoute: ConsoleCustomersIndexRoute,
  ConsoleInventoryIndexRoute: ConsoleInventoryIndexRoute,
  ConsoleOrdersIndexRoute: ConsoleOrdersIndexRoute,
  ConsolePricingIndexRoute: ConsolePricingIndexRoute,
  ConsoleProductsIndexRoute: ConsoleProductsIndexRoute,
  ConsoleReviewsIndexRoute: ConsoleReviewsIndexRoute,
  ConsoleRfqsIndexRoute: ConsoleRfqsIndexRoute,
  ConsoleSettingsIndexRoute: ConsoleSettingsIndexRoute,
  ConsoleSupportIndexRoute: ConsoleSupportIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConsoleRoute: ConsoleRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
