/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as BulkOrdersRouteImport } from './routes/bulk-orders'
import { Route as BusinessRouteRouteImport } from './routes/business/route'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CombosRouteImport } from './routes/combos'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GiftingRouteImport } from './routes/gifting'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountAddressesRouteImport } from './routes/account/addresses'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BulkCategoryRouteImport } from './routes/bulk.$category'
import { Route as BusinessIndexRouteImport } from './routes/business/index'
import { Route as BusinessBulkCartRouteImport } from './routes/business/bulk-cart'
import { Route as BusinessOrdersRouteImport } from './routes/business/orders'
import { Route as BusinessProfileRouteImport } from './routes/business/profile'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as OrderSuccessIdRouteImport } from './routes/order-success.$id'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as AccountOrdersIdRouteImport } from './routes/account/orders/$id'
import { Route as BusinessRfqsIndexRouteImport } from './routes/business/rfqs/index'
import { Route as BusinessRfqsIdRouteImport } from './routes/business/rfqs/$id'
import { Route as BusinessRfqsNewRouteImport } from './routes/business/rfqs/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkOrdersRoute = BulkOrdersRouteImport.update({
  id: '/bulk-orders',
  path: '/bulk-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRouteRoute = BusinessRouteRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CombosRoute = CombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftingRoute = GiftingRouteImport.update({
  id: '/gifting',
  path: '/gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkCategoryRoute = BulkCategoryRouteImport.update({
  id: '/bulk/$category',
  path: '/bulk/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const BusinessBulkCartRoute = BusinessBulkCartRouteImport.update({
  id: '/bulk-cart',
  path: '/bulk-cart',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const BusinessOrdersRoute = BusinessOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const BusinessProfileRoute = BusinessProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessIdRoute = OrderSuccessIdRouteImport.update({
  id: '/order-success/$id',
  path: '/order-success/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AccountRouteRoute,
} as any)
const BusinessRfqsIndexRoute = BusinessRfqsIndexRouteImport.update({
  id: '/rfqs/',
  path: '/rfqs/',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const BusinessRfqsIdRoute = BusinessRfqsIdRouteImport.update({
  id: '/rfqs/$id',
  path: '/rfqs/$id',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const BusinessRfqsNewRoute = BusinessRfqsNewRouteImport.update({
  id: '/rfqs/new',
  path: '/rfqs/new',
  getParentRoute: () => BusinessRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/business': typeof BusinessRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/combos': typeof CombosRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gifting': typeof GiftingRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/quality': typeof QualityRoute
  '/register': typeof RegisterRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/profile': typeof AccountProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bulk/$category': typeof BulkCategoryRoute
  '/business/bulk-cart': typeof BusinessBulkCartRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/business/profile': typeof BusinessProfileRoute
  '/category/$slug': typeof CategorySlugRoute
  '/order-success/$id': typeof OrderSuccessIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/': typeof AccountIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/business/rfqs/$id': typeof BusinessRfqsIdRoute
  '/business/rfqs/new': typeof BusinessRfqsNewRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/business/rfqs/': typeof BusinessRfqsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/combos': typeof CombosRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gifting': typeof GiftingRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/quality': typeof QualityRoute
  '/register': typeof RegisterRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/profile': typeof AccountProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bulk/$category': typeof BulkCategoryRoute
  '/business/bulk-cart': typeof BusinessBulkCartRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/business/profile': typeof BusinessProfileRoute
  '/category/$slug': typeof CategorySlugRoute
  '/order-success/$id': typeof OrderSuccessIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account': typeof AccountIndexRoute
  '/blog': typeof BlogIndexRoute
  '/business': typeof BusinessIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/business/rfqs/$id': typeof BusinessRfqsIdRoute
  '/business/rfqs/new': typeof BusinessRfqsNewRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/business/rfqs': typeof BusinessRfqsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/business': typeof BusinessRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/combos': typeof CombosRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gifting': typeof GiftingRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/quality': typeof QualityRoute
  '/register': typeof RegisterRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/profile': typeof AccountProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bulk/$category': typeof BulkCategoryRoute
  '/business/bulk-cart': typeof BusinessBulkCartRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/business/profile': typeof BusinessProfileRoute
  '/category/$slug': typeof CategorySlugRoute
  '/order-success/$id': typeof OrderSuccessIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/': typeof AccountIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/business/rfqs/$id': typeof BusinessRfqsIdRoute
  '/business/rfqs/new': typeof BusinessRfqsNewRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/business/rfqs/': typeof BusinessRfqsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/business'
    | '/about'
    | '/bulk-orders'
    | '/cart'
    | '/checkout'
    | '/combos'
    | '/contact'
    | '/faq'
    | '/gifting'
    | '/login'
    | '/privacy'
    | '/quality'
    | '/register'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/wishlist'
    | '/account/addresses'
    | '/account/profile'
    | '/blog/$slug'
    | '/bulk/$category'
    | '/business/bulk-cart'
    | '/business/orders'
    | '/business/profile'
    | '/category/$slug'
    | '/order-success/$id'
    | '/product/$slug'
    | '/account/'
    | '/blog/'
    | '/business/'
    | '/account/orders/$id'
    | '/business/rfqs/$id'
    | '/business/rfqs/new'
    | '/account/orders/'
    | '/business/rfqs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bulk-orders'
    | '/cart'
    | '/checkout'
    | '/combos'
    | '/contact'
    | '/faq'
    | '/gifting'
    | '/login'
    | '/privacy'
    | '/quality'
    | '/register'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/wishlist'
    | '/account/addresses'
    | '/account/profile'
    | '/blog/$slug'
    | '/bulk/$category'
    | '/business/bulk-cart'
    | '/business/orders'
    | '/business/profile'
    | '/category/$slug'
    | '/order-success/$id'
    | '/product/$slug'
    | '/account'
    | '/blog'
    | '/business'
    | '/account/orders/$id'
    | '/business/rfqs/$id'
    | '/business/rfqs/new'
    | '/account/orders'
    | '/business/rfqs'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/business'
    | '/about'
    | '/bulk-orders'
    | '/cart'
    | '/checkout'
    | '/combos'
    | '/contact'
    | '/faq'
    | '/gifting'
    | '/login'
    | '/privacy'
    | '/quality'
    | '/register'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/wishlist'
    | '/account/addresses'
    | '/account/profile'
    | '/blog/$slug'
    | '/bulk/$category'
    | '/business/bulk-cart'
    | '/business/orders'
    | '/business/profile'
    | '/category/$slug'
    | '/order-success/$id'
    | '/product/$slug'
    | '/account/'
    | '/blog/'
    | '/business/'
    | '/account/orders/$id'
    | '/business/rfqs/$id'
    | '/business/rfqs/new'
    | '/account/orders/'
    | '/business/rfqs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  BusinessRouteRoute: typeof BusinessRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BulkOrdersRoute: typeof BulkOrdersRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CombosRoute: typeof CombosRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GiftingRoute: typeof GiftingRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  QualityRoute: typeof QualityRoute
  RegisterRoute: typeof RegisterRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  WishlistRoute: typeof WishlistRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BulkCategoryRoute: typeof BulkCategoryRoute
  CategorySlugRoute: typeof CategorySlugRoute
  OrderSuccessIdRoute: typeof OrderSuccessIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-orders': {
      id: '/bulk-orders'
      path: '/bulk-orders'
      fullPath: '/bulk-orders'
      preLoaderRoute: typeof BulkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combos': {
      id: '/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof CombosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifting': {
      id: '/gifting'
      path: '/gifting'
      fullPath: '/gifting'
      preLoaderRoute: typeof GiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk/$category': {
      id: '/bulk/$category'
      path: '/bulk/$category'
      fullPath: '/bulk/$category'
      preLoaderRoute: typeof BulkCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/business/bulk-cart': {
      id: '/business/bulk-cart'
      path: '/bulk-cart'
      fullPath: '/business/bulk-cart'
      preLoaderRoute: typeof BusinessBulkCartRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/business/orders': {
      id: '/business/orders'
      path: '/orders'
      fullPath: '/business/orders'
      preLoaderRoute: typeof BusinessOrdersRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/business/profile': {
      id: '/business/profile'
      path: '/profile'
      fullPath: '/business/profile'
      preLoaderRoute: typeof BusinessProfileRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success/$id': {
      id: '/order-success/$id'
      path: '/order-success/$id'
      fullPath: '/order-success/$id'
      preLoaderRoute: typeof OrderSuccessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/orders/$id': {
      id: '/account/orders/$id'
      path: '/orders/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/business/rfqs/': {
      id: '/business/rfqs/'
      path: '/rfqs'
      fullPath: '/business/rfqs/'
      preLoaderRoute: typeof BusinessRfqsIndexRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/business/rfqs/$id': {
      id: '/business/rfqs/$id'
      path: '/rfqs/$id'
      fullPath: '/business/rfqs/$id'
      preLoaderRoute: typeof BusinessRfqsIdRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/business/rfqs/new': {
      id: '/business/rfqs/new'
      path: '/rfqs/new'
      fullPath: '/business/rfqs/new'
      preLoaderRoute: typeof BusinessRfqsNewRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountOrdersIdRoute: AccountOrdersIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface BusinessRouteRouteChildren {
  BusinessBulkCartRoute: typeof BusinessBulkCartRoute
  BusinessOrdersRoute: typeof BusinessOrdersRoute
  BusinessProfileRoute: typeof BusinessProfileRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  BusinessRfqsIdRoute: typeof BusinessRfqsIdRoute
  BusinessRfqsNewRoute: typeof BusinessRfqsNewRoute
  BusinessRfqsIndexRoute: typeof BusinessRfqsIndexRoute
}

const BusinessRouteRouteChildren: BusinessRouteRouteChildren = {
  BusinessBulkCartRoute: BusinessBulkCartRoute,
  BusinessOrdersRoute: BusinessOrdersRoute,
  BusinessProfileRoute: BusinessProfileRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  BusinessRfqsIdRoute: BusinessRfqsIdRoute,
  BusinessRfqsNewRoute: BusinessRfqsNewRoute,
  BusinessRfqsIndexRoute: BusinessRfqsIndexRoute,
}

const BusinessRouteRouteWithChildren = BusinessRouteRoute._addFileChildren(
  BusinessRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  BusinessRouteRoute: BusinessRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BulkOrdersRoute: BulkOrdersRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CombosRoute: CombosRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GiftingRoute: GiftingRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  QualityRoute: QualityRoute,
  RegisterRoute: RegisterRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  WishlistRoute: WishlistRoute,
  BlogSlugRoute: BlogSlugRoute,
  BulkCategoryRoute: BulkCategoryRoute,
  CategorySlugRoute: CategorySlugRoute,
  OrderSuccessIdRoute: OrderSuccessIdRoute,
  ProductSlugRoute: ProductSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
