import type { AdminSalesPoint } from "@/contract";

/**
 * Fills the gaps in `salesOverTime`.
 *
 * `DashboardService` groups orders by business-timezone day and returns **only days that had
 * orders**. A chart that joined those points directly would draw one straight segment across a
 * quiet week and misreport a shutdown as steady trade — the operator's most consequential possible
 * misreading of this screen, and it happens silently.
 *
 * The days are generated by **stepping the date string**, never by adding 86 400 000 ms to a
 * `Date`. `AdminSalesPoint.date` is already a business-timezone calendar day (plan 9.4), so
 * arithmetic on a `Date` built from it would reintroduce the browser's timezone as a second answer
 * to "what day is it" — and would be wrong twice a year even in the business's own zone, where a
 * DST day is not 24 hours. `Date.UTC` is used purely as a calendar, which is exactly the one thing
 * it is safe for here: no instant derived from it is ever displayed.
 *
 * Returns `[]` for an empty series rather than inventing thirty zero days: an empty database should
 * say "no orders yet", not draw a flat line at zero that looks like measured trade.
 */
export function fillSalesSeries(points: readonly AdminSalesPoint[]): AdminSalesPoint[] {
  if (points.length === 0) return [];

  const known = new Map(points.map((point) => [point.date, point]));
  const dates = [...known.keys()].sort();
  const first = dates[0];
  const last = dates[dates.length - 1];
  if (first === undefined || last === undefined) return [];

  const filled: AdminSalesPoint[] = [];
  let cursor = first;
  // Bounded so a malformed date from the server cannot spin forever: the series is at most 30 days
  // by `SALES_SERIES_DAYS`, and 400 is comfortably past any legitimate widening of that.
  for (let guard = 0; guard < 400 && cursor <= last; guard += 1) {
    filled.push(known.get(cursor) ?? { date: cursor, sales: 0, orders: 0 });
    cursor = nextDay(cursor);
  }
  return filled;
}

function nextDay(date: string): string {
  const [year, month, day] = date.split("-").map(Number);
  if (year === undefined || month === undefined || day === undefined) return date;
  const stepped = new Date(Date.UTC(year, month - 1, day + 1));
  return stepped.toISOString().slice(0, 10);
}
